version: '3'

services:
  external-api:
    container_name: external-api
    image: gabrielarriola/api-loteria
    ports:
      - "8080:8080"

  db:
    container_name: db
    image: mysql:8
    environment:
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=clientsdb
    ports:
      - "3306:3306"

  api:
    container_name: api-parcial
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/clientsdb
      - DIRECCION_API=http://external-api:8080
      - SERVER_PORT=8081
      - APP_URL=http://localhost:8080
    depends_on:
      - external-api
      - db
    ports:
      - "8081:8081"
    restart: on-failure
