version: '3'

services:
  ngrokcont:
    container_name: ngrokcont
    image: ngrok/ngrok
    networks:
      - backnet
    environment:
      - NGROK_AUTHTOKEN=2e3vC4sCSzrWru6zCsGTTIDznE1_7BGy49hUKFVHbq83bAhnw
    command: http backclh:8080
    ports:
      - "4040:4040"


  backclh:
    container_name: backclh
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backnet
    environment:
      - ngrok.url=http://ngrokcont:4040/api/tunnels
    depends_on:
      - ngrokcont
    ports:
      - "8080:8080"

networks:
  backnet: