version: '3'

services:

  db:
    container_name: db
    image: postgres:15.4
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  backclh:
    container_name: backclh
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
    depends_on:
      - db
    ports:
      - "8080:8080"
